version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: excel
      POSTGRES_PASSWORD: password
      POSTGRES_DB: excel_db
    ports:
      - "1234:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
